#!/bin/sh
set -e

rm -rf .io/o
mkdir .io/o

cabal build
cp "$(cabal list-bin arttal)" .io/o

cd .io

mkdir 'o/font'
python i/font.py | tee 'o/font/log'

i/merge.ff \
	o/font/art/ttf/Regular.ttf "/usr/share/fonts/TTF/JetBrainsMono-Regular.ttf" \
	'o/font/art+JetBrainsMono.ttf' "art+JetBrainsMono"
