#!/bin/sh
set -e

mkdir -p .io/o

cabal build
diff "$(cabal list-bin arttal)" .io/o/arttal || {
	rm -rf .io/o/art
	cp "$(cabal list-bin arttal)" .io/o
}

cd .io

rm -rf o/font && mkdir o/font
python i/font.py | tee o/log
